### PR TITLE
Allow Datafile instantiation with local and cloud paths simultaneously

### PR DESCRIPTION
**Pull request by cortadocodes**
## Summary
Improve the `Datafile` interface and allow instantiation with local and cloud paths simultaneously.

### Enhancements
- [x] Allow `Datafile` instantiation with local and cloud paths simultaneously
- [x] Add `cloud_path` property to Datafile

### Fixes
- [x] Ensure `Datafile` serializes with its `cloud_path` and `project_name`

### Refactoring
- [x] Convert `Datafile.cloud_protocol`, `Datafile.bucket_name`, and `Datafile.path_in_bucket` to properties
- [x] Remove redundant `Datafile.reset_local_path` method
- [x] Simplify cloud location setting and getting within `Datafile`

### CODE REVIEW

**Review by thclark — COMMENTED** [review]
This looks good to me, I've been wondering for a while if the natural thing to do is just be explicit about cloud and local paths. It feels like we'll end up with something more intuitive.

Does this affect the stories for cloud file usages in the docs though? 
a. Could any of them be simplified?
b. Do any of them break (I assume not)?

**Comment by cortadocodes** [comment]
> This looks good to me, I've been wondering for a while if the natural thing to do is just be explicit about cloud and local paths. It feels like we'll end up with something more intuitive.
> 
> Does this affect the stories for cloud file usages in the docs though?
> a. Could any of them be simplified?
> b. Do any of them break (I assume not)?

I agree - I think `cloud_path` and `local_path` are more natural, at least for some use cases. The only problem is we also have the required `path` parameter which we need to make `Datafile` pathable but means we also prioritise one of these paths. I'm not sure what to do as we can't have two equal-priority pathables without `Pathable` being used by composition for `cloud_path` and `local_path` in the constructor rather than as a mixin. In this PR, I've made it so you have to specify one of:
* `path` and `cloud_path` where `path` is a local path
* `path` and `local_path` where `path` is a cloud path

As for the user stories, I think they are all unaffected and still valid. This PR just adds new ways of using `Datafile` so I guess new user stories.

**Comment by thclark** [comment]
I think ultimately we may need to deprecate path, and fully embrace the duality of cloud/local.

That'll have implications for pathable, of course, but we'll have to observe user behaviour as to whether the capabilities of pathable are fully used or not.

Can you make an issue capturing this conversation, and tag it with decision-required and architecture etc labels? Chuck it on the twined ecosystem roadmap, and at some point we'll sit down and strategise about what functionality should stay in for v.1 - but we're not ready to do that until there's a few dozen more active users and we can really crystallise their use cases.

**Review by thclark — APPROVED** [review]
...in the meantime this LGTM

**Pull request merged**
